name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true

      - name: Run tests (if any)
        run: |
          if [ -d tests ]; then
            pip install pytest
            pytest -q
          else
            echo "No tests directory found; skipping tests"
          fi

  build-docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/agentic-rag:${{ github.sha }} .

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/agentic-rag:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/agentic-rag:latest
          docker push ghcr.io/${{ github.repository_owner }}/agentic-rag:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/agentic-rag:latest
